export const SQUAT: string = 'squat';
export const BENCH: string = 'bench';
export const PRESS: string = 'press';
export const DEADLIFT: string = 'deadlift';
export const ROWS: string = 'rows';
export const SLDL: string = 'stiff-leg deadlift';
export const DIPS: string = 'dips';
export const PUSHUPS: string = 'pushups';
export const CHINS: string = 'chins';
export const PULLUPS: string = 'pullups';
export const ARMS: string = 'arms';

export const DARK_BLACK = '#222';
export const MED_BLACK = '#333';
export const LIGHT_BLACK = '#444';
export const WHITE = '#F8F8F8';
export const LIGHT_GRAY = '#aaa';
export const DARK_GRAY = '#989898';
export const BRICK = '#92282E';
