export const exercises = {
  SQUAT: 'squat',
  BENCH: 'bench',
  PRESS: 'press',
  DEADLIFT: 'deadlift',
  ROWS: 'rows',
  SLDL: 'stiff-leg deadlift',
  DIPS: 'dips',
  PUSHUPS: 'pushups',
  CHINS: 'chins',
  PULLUPS: 'pullups',
  ARMS: 'arms',
  DIPS_OR_PUSHUPS: `dips or pushups`,
  CHINS_OR_PULLUPS: `chins or pullups`,
};

export const colors = {
  DARK_BLACK: '#222',
  MED_BLACK: '#333',
  LIGHT_BLACK: '#444',
  WHITE: '#F8F8F8',
  LIGHT_GRAY: '#AAA',
  DARK_GRAY: '#3D3D3D',
  MED_GRAY: '#777',
  BRICK: '#92282E',
  RED: '#BD1D26',
  PINK: '#E91E63',
  ORANGE: '#BD562D',
  PALE_BLUE: '#ABC4E7',
  PALE_VIOLET: '#D1D7EC',
  PALE_GREEN: '#B8D8BE',
  PALE_RED: '#E5BEBD',
};
